### ISSUE TITLE
What version of Python?

### ISSUE THREAD

**Issue by nimaocr** [olofmogren/c-rnn-gan#1]
Hi,
Thanks for sharing your code. I was just wondering what version of Python have you used to implement your code? I tried a couple of different versions (e.g., 2.7.9, 2.7.13, 3.5.0,  and 3.5.2), but each had their own problems. For example, the pythonMidi is sucessfully installed with 2.7.9, but it does not support TensorFlow, while 3.5.2 work with TensorFlow, but not pythonMidi! So, I am wondering which version of Python have you used which is compatible with both pythonMidi and TensorFlow.
Thanks,
Nima

**Comment by olofmogren** [comment]
Hi Nima,

I used python 2.7. There are installers for tensorflow for python 2.7, while you probably have the version for python 3 installed. I'm not sure about python-midi.

Good luck!

Olof 

--

Phone: +46-703-969624
Web:  http://mogren.one/
Email: mogren@chalmers.se, olof@mogren.one 

-------- Ursprungligt meddelande --------
Ämne: [olofmogren/c-rnn-gan] What version of Python? (#1)
Från: nimaocr <notifications@github.com>
Till: olofmogren/c-rnn-gan <c-rnn-gan@noreply.github.com>
Kopia: Subscribed <subscribed@noreply.github.com>

**Comment by nimaocr** [comment]
Hi Olof,

Thanks for your response. I guess I know what the problem is. I just noticed that TensorFlow+Python 2.7 is not supported on Windows, which is the OS I am trying to run your code on. I will try it on Linux then. 

Thanks again,
Nima

**Comment by olofmogren** [comment]
That might be the simplest approach, then.
