### ISSUE TITLE
Memory Leak after every session.run

### ISSUE THREAD

**Issue by roreagan** [olofmogren/c-rnn-gan#2]
Hi,
I tried to run rnn-gan.py with command line
`--model small --datadir data/examples/ --traindir data/traindir/ --select_validation_percentage 20 --select_test_percentage 20`
but this program run out of memory.

And I found that during pre-training period every session.run in function _run_epoch_ leaked some memory when debugging. Every 10 "session.run"s cost about 70M RAM so that after 3 epoch of pre-training this program run out of memory.
I don't know how it leaked my memory. I hope anyone could solve this error.

I worked on 8GB memory, GTX850M, Ubuntu 16.04

Thanks
Lvgen

**Comment by olofmogren** [comment]
This may be related to the pre-training re-creating the computation graph when the sequence-length is improved. If you restart training, does it continue to run? Also, you can try to set the pretraining epochs to 0. Does that work? I have tested the code with a Titan-X, with 12GB of memory. But it shouldn't have to eat memory.

**Comment by roreagan** [comment]
I'm sorry for my belated response. It works for me. I think the reason is the re-creating of the computation graph during pre-training. Thank you :)
