### ISSUE TITLE
Ａ question relate to the D structure

### ISSUE THREAD

**Issue by zxiaomzxm** [olofmogren/c-rnn-gan#4]
Hi, I realize a rnn-gan on a sequence data rencently.
But I found the D_loss is close to zero fast and G_loss not converged for a long time when I 
add a RNN in Ｄ-net.And everything is OK when I discard the rnn structure in D-net.Why that could be
happened?Or should Ｉ use the bidirectional rnn structure as your paper used?

**Comment by olofmogren** [comment]
Hi,

What do you mean by "everything is ok"? And what do you mean by "discarding the RNN structure"? What do you have in its pace?

Best regards, Olof

--
Phone: +46-703-969624
Web: http://mogren.one
Email: mogren@chalmers.se, olof@mogren.one

-------- Ursprungligt meddelande --------
Ämne: [olofmogren/c-rnn-gan] Ａ question relate to the D structure (#4)
Från: zxiaomzxm <notifications@github.com>
Till: olofmogren/c-rnn-gan <c-rnn-gan@noreply.github.com>
Kopia: Subscribed <subscribed@noreply.github.com>

**Comment by zxiaomzxm** [comment]
Thanks for your reply.
"everything is ok" means the generate image looks good but the sequence seems has no temporal correlation.
 "discarding the RNN structure" means I just use a vanilla fully connected net instead of vanilla rnn.
I test a bidirectional rnn ,but fails again.It seems that the generator can't deceive the discriminator and generate bad results.

**Comment by olofmogren** [comment]
I see. Does any of the tricks in Salismans et.al. help?

https://arxiv.org/abs/1606.03498

--
Phone: +46-703-969624
Web: http://mogren.one
Email: mogren@chalmers.se, olof@mogren.one

-------- Ursprungligt meddelande --------
Ämne: Re: [olofmogren/c-rnn-gan] Ａ question relate to the D structure (#4)
Från: zxiaomzxm <notifications@github.com>
Till: olofmogren/c-rnn-gan <c-rnn-gan@noreply.github.com>
Kopia: Olof Mogren <olof@mogren.one>,Comment <comment@noreply.github.com>

**Comment by zxiaomzxm** [comment]
I will read this paper.Thanks
