### ISSUE TITLE
Bugs report for your code

### ISSUE THREAD

**Issue by shixianwen** [olofmogren/c-rnn-gan#5]
Hi, my name is Shixian Wen. I am currently a computer science Ph.D. student at University of Southern California.
Your code is great, but I found some small bugs that could be some problems.
1:
in line #250 you cannot define MultiRNNCell([lstm_cell] * FLAGS.num_layers_g, state_is_tuple=True) like this. you should use something like [cell for _ in range(config.num_layers)] in https://github.com/tensorflow/models/blob/master/tutorials/rnn/ptb/ptb_word_lm.py official tutorial. 
The reason is here 
https://stackoverflow.com/questions/45456116/valueerror-trying-to-share-variable-enco-gru-cell-gates-kernel-but-specified-s

2:
you did not update the state c and state h for discriminator and generator:
You were trying to update the state in generator from #557 to #559 for generator, but you comment it out.
You did not update the state of discriminator at all.
see the code in ptb_word_lm.py #402 to #402
The reason is here:
https://stackoverflow.com/questions/40991975/how-are-the-batches-iterated-in-the-ptb-lstm-example-of-tensorflow/40998815#40998815

**Comment by olofmogren** [comment]
Dear Shixian,
Thank you for your comments. Your first comment refers to something that changed in tensorflow after the experiments were done. You will have to make the change according to your comment if you'd like to run this with a more recent vesion of tensorflow. (I don't remember in which version this was changed, but I believe that the published experiments were run with TF 0.11). Your second comment may be right. It was probabily a mistake on my part. Feel free to try with the initialization and see how it performs. I doubt that this will affect the results in any way that is comparable to a language model.
Best regards, Olof
