### ISSUE TITLE
Tensorflow version

### ISSUE THREAD

**Issue by gcunhase** [olofmogren/c-rnn-gan#6]
Hi,
Great work with the code! My question is which Tensorflow version did you use to compile it and is there a 1.3.0 version available?

Thanks in advance

**Comment by olofmogren** [comment]
Hi Gwena,

The experiments were run with TF 0.11. I once started porting it to TF 
1.2, but I haven't had time. Feel free to try it, and send me a pull 
request when it works! Some of the porting issues have been discussed 
above.

Olof

**Comment by liaolinyan2018** [comment]
我的问题是如何让这个代码跑起来呢，您的md文件能否写得更详细一些呢。

**Comment by ShusenTang** [comment]
> 我的问题是如何让这个代码跑起来呢，您的md文件能否写得更详细一些呢。

You must comment in English if you look forward to someone's reply.

**Comment by olofmogren** [comment]
I have now incorporated changes from Dhruv Sharma, so it runs on TF 1.x. Let me know if you have more issues.
