### ISSUE TITLE
Keras

### ISSUE THREAD

**Issue by aryan-f** [olofmogren/c-rnn-gan#8]
Hi.
Great work. Could you please provide a Keras implementation of the model? I had an idea for testing the model for signal synthesis of some kind but I'm not familiar with TF. 
Thanks

**Comment by olofmogren** [comment]
Hi, anyone with the right competence is welcome to port this to Keras. In fact, Keras is just a thin layer on top of TF, so while this could improve readability, it would not change the code much.
